"""Demo of ctx-zip style code generation approach.

This example shows how to use code generation instead of HTTP servers
to make tools available in sandbox environments, especially useful for
cloud sandboxes like E2B that can't reach localhost.
"""

import asyncio

from llmling_agent.resource_providers.codemode.code_execution_provider import (
    CodeExecutionProvider,
)
from llmling_agent.tools.base import Tool
from llmling_agent_config.execution_environments import LocalExecutionEnvironmentConfig


def add_numbers(x: int, y: int) -> int:
    """Add two numbers together.

    Args:
        x: First number
        y: Second number

    Returns:
        Sum of x and y
    """
    return x + y


def multiply_numbers(x: int, y: int) -> int:
    """Multiply two numbers together.

    Args:
        x: First number
        y: Second number

    Returns:
        Product of x and y
    """
    return x * y


async def fetch_weather(city: str, country: str = "US") -> dict:
    """Fetch weather information for a city.

    Args:
        city: Name of the city
        country: Country code (default: US)

    Returns:
        Weather information dict
    """
    # Simulate API call
    return {
        "city": city,
        "country": country,
        "temperature": 22,
        "condition": "sunny",
        "humidity": 65,
    }


async def demo_http_server_approach():
    """Demo original HTTP server approach (works with local/docker)."""
    print("=== HTTP Server Approach ===")
    tools = [
        Tool.from_callable(add_numbers),
        Tool.from_callable(multiply_numbers),
        Tool.from_callable(fetch_weather),
    ]
    config = LocalExecutionEnvironmentConfig()

    provider = CodeExecutionProvider.from_tools(tools, config, server_port=9876)

    async with provider:
        print("Tool description:")
        print(provider.get_tool_description())
        print("\nExecuting code with HTTP calls...")

        # Code that makes HTTP calls to FastAPI server
        code = """
import httpx

# These would normally be generated by the system
async def add_numbers(x, y):
    async with httpx.AsyncClient() as client:
        response = await client.post("http://localhost:9876/tools/add_numbers",
                                   json={"x": x, "y": y})
        return response.json()

# Execute tool
result = await add_numbers(15, 27)
_result = result
print(f"HTTP Server result: {result}")
"""
        result = await provider.execute_code(code)
        print(f"Final result: {result.result}")


if __name__ == "__main__":
    asyncio.run(demo_http_server_approach())
