agents:
  overseer:
    name: "Download Coordinator"
    description: "Coordinates downloads using registered worker tools"
    model: openai:gpt-5-mini
    system_prompts:
      - "You coordinate file downloads using the worker tools registered with you. Use all available worker tools to download the requested file."

  file_getter_1:
    name: "File Downloader Worker"
    description: "Downloads files from URLs"
    model: openai:gpt-5-mini
    system_prompts:
      - "You download files from URLs using the download_file tool."
    tools:
      - llmling_agent_tools.download_file
