agents:
  coordinator:
    model: openai:o4-mini
    system_prompts:
      - You select the most suitable expert(s) for each task.

  database_expert:
    model: openai:o4-mini
    description: Expert in SQL optimization and database design.

  frontend_dev:
    model: openai:o4-mini
    description: Specialist in React and modern web interfaces.

  security_expert:
    model: openai:o4-mini
    description: Expert in penetration testing and security audits.
